[package]
name = "can-display"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.0"
defmt = "0.3.9"
defmt-rtt = "0.4"
embassy-embedded-hal = "0.2.0"
embassy-executor = { version = "0.6.0", features = ["executor-thread", "integrated-timers"] }
embassy-futures = "0.1.1"
embassy-stm32 = { version = "0.1.0", features = ["stm32l471rg", "defmt", "memory-x", "unstable-pac", "memory-x", "time-driver-any", "exti", "chrono"] }
embassy-sync = "0.6.1"
embassy-time = { version = "0.3.2", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
futures = { version = "0.3.30", default-features = false, features = ["async-await"] }
heapless = "0.8.0"
panic-probe = { version = "0.3", features = ["print-defmt"] }
static_cell = { version = "2.0.0" }
embedded-can = "0.4.1"
embedded-hal = "1.0.0"
embedded-hal-bus = "0.2.0"
nb = "1.1.0"
epd-waveshare = "0.6.0"
embedded-graphics = "0.8.1"
profont = "0.7.0"
arrform = "0.1.1"


[target.'cfg(target_arch = "arm")'.dependencies]
embassy-executor = { version = "0.6.0", features = ["arch-cortex-m", "task-arena-size-32768"] }

[target.'cfg(any(unix,windows))'.dependencies]
embassy-executor = { version = "0.6.0", features = ["arch-std"] }
embassy-sync = { version = "0.6.1", features = ["std"] }

[patch.crates-io]
embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy", rev = "8a5d1454a40f8de7217d9bcbbe54ac9998340ab8" }
embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "8a5d1454a40f8de7217d9bcbbe54ac9998340ab8" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy", rev = "8a5d1454a40f8de7217d9bcbbe54ac9998340ab8" }
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy", rev = "8a5d1454a40f8de7217d9bcbbe54ac9998340ab8" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", rev = "8a5d1454a40f8de7217d9bcbbe54ac9998340ab8" }
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "8a5d1454a40f8de7217d9bcbbe54ac9998340ab8" }
embedded-can = { git = "https://github.com/rust-embedded/embedded-hal/", rev = "6a7d02687db8dbfd16b55f29ade3e48bbbedbcde" }

[profile.release]
lto = true
debug = true

[profile.dev]
opt-level = 3
lto = true
