[target.'cfg(all(target_arch = "arm", target_os = "none"))']

runner = [
  "probe-rs",
  "run",
  "--chip", "STM32L471RGTx",
  "--connect-under-reset",
  "--catch-reset",
  "--catch-hardfault",
  "--always-print-stacktrace",
  "--preverify", # Do not flash if up-to-date
  "--verify", # Verify after flashing also
  "--log-format", "{L} {t} {f}:{l} {s}",
]


[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"
