[package]
name = "eoi-flash-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
can-socket = { version = "0.3", features = ["tokio"] }
elf = "0.7"
crc = "3"
eoi-boot-api = { path = "../boot-api" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
thiserror = "2"
env_logger = "0.11"
log = "0.4"
