[package]
name = "eoi-can-to-grpc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "eoi-can-to-grpc"
path = "src/main.rs"

[dependencies]
eoi-can-decoder = { path = "../eoi-can-decoder" }

clap = { workspace = true, features = ["env"] }
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
embedded-can.workspace = true

heapless = "0.8.0"
prost = "0.13"
prost-types = "0.13"
rand = "0.8"
tokio-stream = { version = "0.1", features = ["sync"] }
tonic = { version = "0.13", features = ["transport"] }
tonic-web = "0.13"
tower-http = { version = "0.6", features = ["cors"] }
http = "1"
parking_lot = "0.12"

[target.'cfg(target_os = "linux")'.dependencies]
socketcan.workspace = true

[build-dependencies]
tonic-build = "0.13"
protoc-bin-vendored = "3"
